### PR TITLE
Kinetic release prep

### PR DESCRIPTION
**Pull request by tfoote**
@wjwwood @mikeferguson is this what's needed for releasing bfl into kinetic?

### CODE REVIEW

**Comment by wjwwood** [comment]
I wouldn't duplicate the `tracks.yaml` entry, but the `package.xml` is ok.

**Comment by mikeferguson** [comment]
I honestly never remember how to release this package, and end up looking it up each time we have a new distro

**Comment by mikeferguson** [comment]
Do we also need to create a patches/kinetic branch?

**Comment by tfoote** [comment]
I was trying to duplicate the removed upstream import while adding new debian rules in the tracks.yaml I just fixed the references to the rosdistro.

@mikeferguson I think we're using the directtory overlay method instead of a branch

**Comment by wjwwood** [comment]
Is the upstream no longer there? Why do the import steps need to be removed?

I'm not sure copying the track.yaml entry is going to work. At the very least the `release_inc` should be reset to 0 or maybe removed (don't know which).

**Comment by mikeferguson** [comment]
Yes, the upstream is no longer there -- we ran into that during the jade release

**Comment by tfoote** [comment]
I reset the debinc number.

**Comment by tfoote** [comment]
@mikeferguson do you mind if I merge and try running bloom on it tonight?

**Comment by mikeferguson** [comment]
@tfoote, go right ahead -- I'm pretty sure last time around @wjwwood actually ended up making this repo work for me, so I really don't recall the steps involved

**Pull request merged**
